// import { Geist, Geist_Mono } from "next/font/google";
// import { Pixelify_Sans } from "next/font/google";
import { Silkscreen } from "next/font/google";
import styles from "@/src/app/layout.module.css"
import baseContainer from "@/src/app/baseContainer.module.css"
// import Search from "../ui/search";
import { SearchProvider } from "@/src/contexts/searchContext";
import "./globals.css";
import { CategoriesProvider } from "@/src/contexts/categoriesContext"
import Link from "next/link";
import CookieBanner from "@/src/ui/cookieBanner"
import Header from "@/src/ui/header"

const silkscreen = Silkscreen({
  variable: "--font-silkscreen",
  subsets: ["latin"],
  weight: ["400", "700"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const year = new Date().getFullYear();

  return (
    <html lang="en">
      <body className={`${silkscreen.variable}`}>
        <CategoriesProvider>
          <SearchProvider>
            <div className={baseContainer.baseContainer}>
              <Header>
                {/* <span className={`${styles.left} ${styles.circle}`} /> */}
                <Link href="/" className={`${styles.left}`}>
                  <img src="/icons/logo-etg.svg" className={`${styles.logo} ${styles.left}`}></img>
                </Link>
                <nav className={`${styles.nav} ${styles.right}`}>
                  <ul>
                    <li><Link href="/faq">FAQ</Link></li>
                    <li><Link href="/about">About</Link></li>
                    <li><Link href="/contact">Contact</Link></li>
                  </ul>
                </nav>
                {/* <Search className={styles.right} /> */}
                {/* <div className={`${styles.right}`}>Settings</div> */}
                {/* <BurgerMenu /> */}
              </Header>
            </div>
            {children}
            <div className={baseContainer.baseContainer}>
              <div className={`${styles.footer}`}>
                <hr className={`${styles.hrBig}`}></hr>
                <div className={`${styles.nav} ${styles.links}`}>
                  <ul>
                    <li><Link href="/">Home</Link></li>
                    <li><Link href="/faq">FAQ</Link></li>
                    <li><Link href="/about">About</Link></li>
                    <li><Link href="/contact">Contact</Link></li>
                  </ul>
                </div>
                <hr className={`${styles.hrSmall}`}></hr>
                <div className={`${styles.disclaimer}`}>
                  <span>
                    This project is a fan-made, non-commercial website and is not an official product of Dodge Roll or Devolver Digital.
                  </span>
                  <span>
                    All data and images are sourced from the <a href="https://enterthegungeon.wiki.gg/">Enter the Gungeon Wiki</a> and are used under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0 license</a>.
                  </span>
                  <span>
                    © {year} All rights reserved.
                  </span>
                </div>
              </div>
            </div>
          </SearchProvider>
        </CategoriesProvider>

        <CookieBanner></CookieBanner>
      </body>
    </html>
  );
}
